name: hello world sam

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "first jobs hello"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "second job goodbye world"
        shell: bash